# Generated by Django 3.1.3 on 2021-01-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseCode', models.CharField(max_length=8)),
                ('courseName', models.CharField(max_length=100)),
            ],
        ),
    ]
