# Generated by Django 3.1.3 on 2021-01-12 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursePlanner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='query',
            new_name='text',
        ),
    ]
