# Generated by Django 3.1.3 on 2021-01-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursePlanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseCode',
            field=models.CharField(max_length=20),
        ),
    ]
