# Generated by Django 3.1.3 on 2021-01-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursePlanner', '0004_auto_20210115_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='myGrade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
