# Generated by Django 3.1.3 on 2021-01-12 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursePlanner', '0004_link_query'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Query',
        ),
        migrations.AddField(
            model_name='link',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coursePlanner.course'),
            preserve_default=False,
        ),
    ]
