# Generated by Django 3.1.3 on 2021-01-12 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursePlanner', '0006_query'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='query',
            options={'verbose_name_plural': 'queries'},
        ),
    ]
