# Generated by Django 3.1.3 on 2021-01-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursePlanner', '0007_auto_20210112_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.CharField(max_length=1000),
        ),
    ]
