# Generated by Django 3.1.3 on 2021-01-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursePlanner', '0003_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='myGrade',
            field=models.IntegerField(null=True),
        ),
    ]
